-- ============================================================
-- DATABASE DEFINITION - G03
-- Campus Space Management System
-- Target DBMS          : Microsoft SQL Server
-- Logical design input : outputs/03-logical-design-G03.md
-- Validation input     : outputs/04-design-validation-G03.md
-- Generated by         : openai/gpt-5.5 database-definition-implementation-engineer
-- ============================================================
--
-- DDL-STAGE ASSUMPTIONS
-- [ddl-stage] The command requested `.opencode/agent/database-implementation-engineer.md`,
--             but the repository contains `.opencode/agent/database-definition-implementation-engineer.md`.
--             The available database definition implementation agent was used.
-- [ddl-stage] The implementation self-check rubric file present in the repository is
--             `.opencode/evaluation/ddl-rubric.md`; no file named
--             `.opencode/evaluation/ddl-implementation-rubric.md` exists.
-- [ddl-stage] Surrogate integer primary keys use SQL Server IDENTITY(1,1), matching the
--             logical design's `INT IDENTITY(1,1)` columns.
-- [ddl-stage] Non-clustered indexes are created on all foreign-key columns only, for FK join
--             performance, as allowed by the implementation agent's index rule.
-- [ddl-stage] The script uses a documented drop/recreate sequence for idempotent demo execution.
-- [ddl-stage] Trigger stubs/enforcement shells use AFTER INSERT, UPDATE with RAISERROR/ROLLBACK.
-- [ddl-stage] The current logical design includes APPROVAL_DECISION.decision_outcome and the named
--             CK_APPROVAL_DECISION_rejection_reason CHECK; this DDL implements that authoritative
--             design rather than an older no-decision-outcome variant.
--
-- UPSTREAM ASSUMPTIONS CARRIED FORWARD
-- [upstream] Facility ID, Booking ID, Approval Decision ID, Usage Session ID, and Maintenance
--            Record ID were proposed upstream; the logical design implements them as surrogate
--            INT IDENTITY primary keys.
-- [upstream] decision_outcome is included on APPROVAL_DECISION as a derived attribute because
--            the source names approved/rejected outcomes.
-- [upstream] HAS_USAGE_SESSION remains 1 to 0..1; USAGE_SESSION.booking_id is therefore unique.
-- [upstream] "Closed" in the booking restriction is treated as SPACE.current_status =
--            'Temporarily closed'.
-- [upstream] No separate booking type/category is introduced; purpose_of_use is the source-named fact.
-- [upstream] Nullable notes/details and lifecycle-dependent fields remain nullable as documented
--            in the logical design.
--
-- OPEN QUESTIONS CARRIED FORWARD
-- (See -- OPEN QUESTION blocks at affected tables for detail.)
-- Q1.  How is SPACE.usage_policy enforced, if at all?
-- Q2.  How should same-space overlapping approved bookings be enforced/concurrency-controlled?
-- Q3.  How should unavailable-space booking prevention interact with SPACE and MAINTENANCE_RECORD?
-- Q4.  What triggers Cancelled and No-show booking statuses, and from which statuses?
-- Q5.  Must every approved/rejected booking have exactly one APPROVAL_DECISION row?
-- Q6.  Which roles are included in generic "Staff" view permissions?
-- Q7.  Which roles may report maintenance issues?
-- Q8.  Which roles may assign maintenance staff?
-- Q9.  What are the allowed values/transitions for MAINTENANCE_RECORD.status?
-- Q10. Does recording APPROVAL_DECISION automatically update BOOKING_REQUEST.status?
-- Q11. Does MAINTENANCE_RECORD.status automatically update SPACE.current_status?
-- Q12. Are department administrators intended to have responsibilities beyond submitting bookings?
-- Q13. What are the allowed values for USER_ACCOUNT.account_status?
-- Q14. Must BOOKING_REQUEST.expected_number_of_participants <= SPACE.capacity?
-- Q15. Are any bookings exempt from approval workflow, such as Pending -> Checked in directly?
-- ============================================================

-- ============================================================
-- DROP / RECREATE BLOCK FOR IDEMPOTENT DEMO EXECUTION
-- ============================================================
IF OBJECT_ID('dbo.TR_USAGE_SESSION_CompletionConsistency', 'TR') IS NOT NULL DROP TRIGGER dbo.TR_USAGE_SESSION_CompletionConsistency;
IF OBJECT_ID('dbo.TR_USAGE_SESSION_CompletionRoleCheck', 'TR') IS NOT NULL DROP TRIGGER dbo.TR_USAGE_SESSION_CompletionRoleCheck;
IF OBJECT_ID('dbo.TR_USAGE_SESSION_CheckInRoleCheck', 'TR') IS NOT NULL DROP TRIGGER dbo.TR_USAGE_SESSION_CheckInRoleCheck;
IF OBJECT_ID('dbo.TR_APPROVAL_DECISION_RejectionReason', 'TR') IS NOT NULL DROP TRIGGER dbo.TR_APPROVAL_DECISION_RejectionReason;
IF OBJECT_ID('dbo.TR_APPROVAL_DECISION_RoleCheck', 'TR') IS NOT NULL DROP TRIGGER dbo.TR_APPROVAL_DECISION_RoleCheck;
IF OBJECT_ID('dbo.TR_BOOKING_REQUEST_SpaceAvailability', 'TR') IS NOT NULL DROP TRIGGER dbo.TR_BOOKING_REQUEST_SpaceAvailability;
IF OBJECT_ID('dbo.TR_BOOKING_REQUEST_NoOverlap', 'TR') IS NOT NULL DROP TRIGGER dbo.TR_BOOKING_REQUEST_NoOverlap;
GO

IF OBJECT_ID('dbo.MAINTENANCE_RECORD', 'U') IS NOT NULL DROP TABLE dbo.MAINTENANCE_RECORD;
IF OBJECT_ID('dbo.USAGE_SESSION', 'U') IS NOT NULL DROP TABLE dbo.USAGE_SESSION;
IF OBJECT_ID('dbo.APPROVAL_DECISION', 'U') IS NOT NULL DROP TABLE dbo.APPROVAL_DECISION;
IF OBJECT_ID('dbo.BOOKING_REQUEST', 'U') IS NOT NULL DROP TABLE dbo.BOOKING_REQUEST;
IF OBJECT_ID('dbo.SPACE_FACILITY', 'U') IS NOT NULL DROP TABLE dbo.SPACE_FACILITY;
IF OBJECT_ID('dbo.FACILITY', 'U') IS NOT NULL DROP TABLE dbo.FACILITY;
IF OBJECT_ID('dbo.SPACE', 'U') IS NOT NULL DROP TABLE dbo.SPACE;
IF OBJECT_ID('dbo.USER_ACCOUNT', 'U') IS NOT NULL DROP TABLE dbo.USER_ACCOUNT;
GO

-- ============================================================
-- TABLE: USER_ACCOUNT
-- Source: Logical Design §2.1
-- ============================================================
CREATE TABLE dbo.USER_ACCOUNT (
    user_account_id INT IDENTITY(1,1) NOT NULL,
    user_id NVARCHAR(50) NOT NULL,
    full_name NVARCHAR(200) NOT NULL,
    email NVARCHAR(254) NOT NULL,
    phone_number NVARCHAR(30) NULL,
    role NVARCHAR(40) NOT NULL,
    department NVARCHAR(120) NULL,
    account_status NVARCHAR(40) NOT NULL,
    CONSTRAINT PK_USER_ACCOUNT PRIMARY KEY (user_account_id),
    CONSTRAINT UQ_USER_ACCOUNT_user_id UNIQUE (user_id),
    CONSTRAINT UQ_USER_ACCOUNT_email UNIQUE (email),
    CONSTRAINT CK_USER_ACCOUNT_role CHECK (role IN (N'Student', N'Lecturer', N'Teaching Assistant', N'Facility Staff', N'Department Administrator', N'Facility Manager'))
);
GO

-- OPEN QUESTION Q13: What are the allowed values for USER_ACCOUNT.account_status?
-- Affected table/column: USER_ACCOUNT.account_status
-- No CHECK constraint has been added because the logical design says no upstream values are available.
-- Resolve upstream before adding an account_status allowed-value constraint.

-- OPEN QUESTION Q6: Which listed user roles are included in generic "Staff" view permissions?
-- Affected table/column: USER_ACCOUNT.role
-- No authorization view, trigger, or constraint has been added for this question.
-- Resolve upstream before adding staff-view permission enforcement.

-- OPEN QUESTION Q12: Are department administrators intended to have responsibilities beyond submitting booking requests?
-- Affected table/column: USER_ACCOUNT.role
-- No additional permission table, trigger, or role rule has been added for this question.

-- ============================================================
-- TABLE: SPACE
-- Source: Logical Design §2.2
-- ============================================================
CREATE TABLE dbo.SPACE (
    space_id INT IDENTITY(1,1) NOT NULL,
    unique_space_code NVARCHAR(50) NOT NULL,
    space_name NVARCHAR(200) NOT NULL,
    space_type NVARCHAR(80) NOT NULL,
    building NVARCHAR(120) NOT NULL,
    floor NVARCHAR(40) NOT NULL,
    room_number NVARCHAR(40) NOT NULL,
    capacity INT NOT NULL,
    current_status NVARCHAR(40) NOT NULL,
    usage_policy NVARCHAR(1000) NULL,
    CONSTRAINT PK_SPACE PRIMARY KEY (space_id),
    CONSTRAINT UQ_SPACE_unique_space_code UNIQUE (unique_space_code),
    CONSTRAINT CK_SPACE_capacity_positive CHECK (capacity > 0),
    CONSTRAINT CK_SPACE_current_status CHECK (current_status IN (N'Available', N'In use', N'Under maintenance', N'Temporarily closed', N'Retired'))
);
GO

-- OPEN QUESTION Q1: How is SPACE.usage_policy enforced, if at all, when evaluating a booking request?
-- Affected table/column: SPACE.usage_policy
-- No constraint or trigger has been added for usage_policy enforcement.
-- Resolve upstream before adding enforcement logic.

-- OPEN QUESTION Q11: Does MAINTENANCE_RECORD.status automatically update SPACE.current_status?
-- Affected tables/columns: SPACE.current_status, MAINTENANCE_RECORD.status
-- No synchronization trigger has been added because the direction of dependency is unresolved.
-- Resolve upstream before adding status synchronization logic.

-- ============================================================
-- TABLE: FACILITY
-- Source: Logical Design §2.3
-- ============================================================
CREATE TABLE dbo.FACILITY (
    facility_id INT IDENTITY(1,1) NOT NULL,
    facility_name NVARCHAR(120) NOT NULL,
    CONSTRAINT PK_FACILITY PRIMARY KEY (facility_id)
);
GO

-- No allowed-value CHECK on FACILITY.facility_name: logical design classifies it as an open equipment catalog.

-- ============================================================
-- TABLE: SPACE_FACILITY
-- Source: Logical Design §2.4
-- ============================================================
CREATE TABLE dbo.SPACE_FACILITY (
    space_facility_id INT IDENTITY(1,1) NOT NULL,
    space_id INT NOT NULL,
    facility_id INT NOT NULL,
    CONSTRAINT PK_SPACE_FACILITY PRIMARY KEY (space_facility_id),
    CONSTRAINT UQ_SPACE_FACILITY_space_id_facility_id UNIQUE (space_id, facility_id),
    CONSTRAINT FK_SPACE_FACILITY_space_id FOREIGN KEY (space_id) REFERENCES dbo.SPACE(space_id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT FK_SPACE_FACILITY_facility_id FOREIGN KEY (facility_id) REFERENCES dbo.FACILITY(facility_id) ON DELETE CASCADE ON UPDATE NO ACTION
);
GO

-- Indexes on FK columns
CREATE NONCLUSTERED INDEX IX_SPACE_FACILITY_space_id ON dbo.SPACE_FACILITY (space_id);
CREATE NONCLUSTERED INDEX IX_SPACE_FACILITY_facility_id ON dbo.SPACE_FACILITY (facility_id);
GO

-- ============================================================
-- TABLE: BOOKING_REQUEST
-- Source: Logical Design §2.5
-- ============================================================
CREATE TABLE dbo.BOOKING_REQUEST (
    booking_id INT IDENTITY(1,1) NOT NULL,
    requester_user_account_id INT NOT NULL,
    space_id INT NOT NULL,
    requested_start_time DATETIME2(0) NOT NULL,
    requested_end_time DATETIME2(0) NOT NULL,
    purpose_of_use NVARCHAR(40) NOT NULL,
    expected_number_of_participants INT NOT NULL,
    status NVARCHAR(40) NOT NULL,
    CONSTRAINT PK_BOOKING_REQUEST PRIMARY KEY (booking_id),
    CONSTRAINT FK_BOOKING_REQUEST_requester_user_account_id FOREIGN KEY (requester_user_account_id) REFERENCES dbo.USER_ACCOUNT(user_account_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_BOOKING_REQUEST_space_id FOREIGN KEY (space_id) REFERENCES dbo.SPACE(space_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT CK_BOOKING_REQUEST_requested_time_order CHECK (requested_end_time > requested_start_time),
    CONSTRAINT CK_BOOKING_REQUEST_expected_participants_positive CHECK (expected_number_of_participants > 0),
    CONSTRAINT CK_BOOKING_REQUEST_purpose_of_use CHECK (purpose_of_use IN (N'Lecture', N'Examination', N'Seminar', N'Workshop', N'Meeting', N'Student activity', N'Administrative event')),
    CONSTRAINT CK_BOOKING_REQUEST_status CHECK (status IN (N'Pending', N'Approved', N'Rejected', N'Cancelled', N'Checked in', N'Completed', N'No-show'))
);
GO

-- Indexes on FK columns
CREATE NONCLUSTERED INDEX IX_BOOKING_REQUEST_requester_user_account_id ON dbo.BOOKING_REQUEST (requester_user_account_id);
CREATE NONCLUSTERED INDEX IX_BOOKING_REQUEST_space_id ON dbo.BOOKING_REQUEST (space_id);
GO

-- ------------------------------------------------------------
-- IMPLEMENTATION REQUIRED: No overlapping approved bookings
-- BR: BR-9 (also tied to BR-8 approved status)
-- Tables: BOOKING_REQUEST
-- Enforce: Same space cannot have two approved bookings with overlapping requested time periods.
-- ------------------------------------------------------------
CREATE TRIGGER dbo.TR_BOOKING_REQUEST_NoOverlap ON dbo.BOOKING_REQUEST
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM inserted i
        JOIN dbo.BOOKING_REQUEST b
          ON b.space_id = i.space_id
         AND b.booking_id <> i.booking_id
         AND b.status = N'Approved'
         AND i.status = N'Approved'
         AND i.requested_start_time < b.requested_end_time
         AND i.requested_end_time > b.requested_start_time
    )
    BEGIN
        RAISERROR(N'Approved booking overlaps an existing approved booking for the same space.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END;
END;
GO

-- ------------------------------------------------------------
-- IMPLEMENTATION REQUIRED: Unavailable-space booking prevention
-- BR: BR-10, BR-19
-- Tables: BOOKING_REQUEST, SPACE
-- Enforce: Prevent booking rows for spaces whose current_status is Under maintenance,
--          Temporarily closed, or Retired.
-- ------------------------------------------------------------
CREATE TRIGGER dbo.TR_BOOKING_REQUEST_SpaceAvailability ON dbo.BOOKING_REQUEST
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM inserted i
        JOIN dbo.SPACE s ON s.space_id = i.space_id
        WHERE s.current_status IN (N'Under maintenance', N'Temporarily closed', N'Retired')
    )
    BEGIN
        RAISERROR(N'Space is under maintenance, temporarily closed, or retired and cannot be booked.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END;
END;
GO

-- OPEN QUESTION Q2: How should same-space overlapping approved bookings be enforced/concurrency-controlled?
-- Affected table/columns: BOOKING_REQUEST.space_id, requested_start_time, requested_end_time, status
-- A trigger has been provided as required, but transaction isolation/concurrency policy remains to be confirmed.

-- OPEN QUESTION Q3: How should unavailable-space booking prevention interact with SPACE and MAINTENANCE_RECORD?
-- Affected tables/columns: BOOKING_REQUEST.space_id, SPACE.current_status, MAINTENANCE_RECORD.status
-- The trigger checks SPACE.current_status only. No active-maintenance-record logic has been added.

-- OPEN QUESTION Q4: What triggers Cancelled and No-show booking status transitions, and from which statuses?
-- Affected table/column: BOOKING_REQUEST.status
-- No transition-state trigger has been added beyond the allowed-value CHECK.

-- OPEN QUESTION Q14: Must expected_number_of_participants <= SPACE.capacity?
-- Affected tables/columns: BOOKING_REQUEST.expected_number_of_participants, SPACE.capacity
-- No cross-table capacity CHECK/trigger has been added because upstream did not require the comparison.

-- OPEN QUESTION Q15: Are any bookings exempt from approval workflow, such as Pending -> Checked in directly?
-- Affected table/column: BOOKING_REQUEST.status
-- No approval-workflow transition trigger has been added.

-- ============================================================
-- TABLE: APPROVAL_DECISION
-- Source: Logical Design §2.6
-- ============================================================
CREATE TABLE dbo.APPROVAL_DECISION (
    approval_decision_id INT IDENTITY(1,1) NOT NULL,
    booking_id INT NOT NULL,
    decision_maker_user_account_id INT NOT NULL,
    decision_outcome NVARCHAR(20) NOT NULL,
    decision_time DATETIME2(0) NOT NULL,
    decision_note NVARCHAR(1000) NULL,
    rejection_reason NVARCHAR(1000) NULL,
    CONSTRAINT PK_APPROVAL_DECISION PRIMARY KEY (approval_decision_id),
    CONSTRAINT FK_APPROVAL_DECISION_booking_id FOREIGN KEY (booking_id) REFERENCES dbo.BOOKING_REQUEST(booking_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_APPROVAL_DECISION_decision_maker_user_account_id FOREIGN KEY (decision_maker_user_account_id) REFERENCES dbo.USER_ACCOUNT(user_account_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT CK_APPROVAL_DECISION_decision_outcome CHECK (decision_outcome IN (N'Approved', N'Rejected')),
    CONSTRAINT CK_APPROVAL_DECISION_rejection_reason CHECK (decision_outcome <> N'Rejected' OR rejection_reason IS NOT NULL)
);
GO

-- Indexes on FK columns
CREATE NONCLUSTERED INDEX IX_APPROVAL_DECISION_booking_id ON dbo.APPROVAL_DECISION (booking_id);
CREATE NONCLUSTERED INDEX IX_APPROVAL_DECISION_decision_maker_user_account_id ON dbo.APPROVAL_DECISION (decision_maker_user_account_id);
GO

-- ------------------------------------------------------------
-- IMPLEMENTATION REQUIRED: Approval decision maker role restriction
-- BR: BR-11, BR-12
-- Tables: APPROVAL_DECISION, USER_ACCOUNT
-- Enforce: Decision maker must have role Facility Staff or Facility Manager.
-- ------------------------------------------------------------
CREATE TRIGGER dbo.TR_APPROVAL_DECISION_RoleCheck ON dbo.APPROVAL_DECISION
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM inserted i
        JOIN dbo.USER_ACCOUNT u ON u.user_account_id = i.decision_maker_user_account_id
        WHERE u.role NOT IN (N'Facility Staff', N'Facility Manager')
    )
    BEGIN
        RAISERROR(N'Approval decision maker must be Facility Staff or Facility Manager.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END;
END;
GO

-- ------------------------------------------------------------
-- IMPLEMENTATION REQUIRED: Rejected decision rejection reason
-- BR: BR-13
-- Tables: APPROVAL_DECISION
-- Enforce: When decision_outcome = Rejected, rejection_reason must be non-null.
-- Note: This rule is already enforced by CK_APPROVAL_DECISION_rejection_reason.
--       Trigger shell retained to satisfy implementation-stub traceability.
-- ------------------------------------------------------------
CREATE TRIGGER dbo.TR_APPROVAL_DECISION_RejectionReason ON dbo.APPROVAL_DECISION
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM inserted i
        WHERE i.decision_outcome = N'Rejected'
          AND i.rejection_reason IS NULL
    )
    BEGIN
        RAISERROR(N'Rejected approval decisions require a rejection reason.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END;
END;
GO

-- OPEN QUESTION Q5: Must every approved/rejected booking have exactly one APPROVAL_DECISION row?
-- Affected tables/columns: BOOKING_REQUEST.status, APPROVAL_DECISION.booking_id
-- No UNIQUE constraint is added to APPROVAL_DECISION.booking_id because logical design preserves 0..* decision history.

-- OPEN QUESTION Q10: Does recording APPROVAL_DECISION automatically update BOOKING_REQUEST.status?
-- Affected tables/columns: APPROVAL_DECISION.decision_outcome, BOOKING_REQUEST.status
-- No status synchronization trigger has been added.

-- ============================================================
-- TABLE: USAGE_SESSION
-- Source: Logical Design §2.7
-- ============================================================
CREATE TABLE dbo.USAGE_SESSION (
    usage_session_id INT IDENTITY(1,1) NOT NULL,
    booking_id INT NOT NULL,
    checked_in_by_user_account_id INT NOT NULL,
    completed_by_user_account_id INT NULL,
    actual_start_time DATETIME2(0) NOT NULL,
    initial_condition_of_space NVARCHAR(1000) NOT NULL,
    actual_end_time DATETIME2(0) NULL,
    final_condition_of_space NVARCHAR(1000) NULL,
    usage_notes NVARCHAR(1000) NULL,
    CONSTRAINT PK_USAGE_SESSION PRIMARY KEY (usage_session_id),
    CONSTRAINT FK_USAGE_SESSION_booking_id FOREIGN KEY (booking_id) REFERENCES dbo.BOOKING_REQUEST(booking_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_USAGE_SESSION_checked_in_by_user_account_id FOREIGN KEY (checked_in_by_user_account_id) REFERENCES dbo.USER_ACCOUNT(user_account_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_USAGE_SESSION_completed_by_user_account_id FOREIGN KEY (completed_by_user_account_id) REFERENCES dbo.USER_ACCOUNT(user_account_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT UQ_USAGE_SESSION_booking_id UNIQUE (booking_id),
    CONSTRAINT CK_USAGE_SESSION_actual_time_order CHECK (actual_end_time IS NULL OR actual_end_time > actual_start_time),
    CONSTRAINT CK_USAGE_SESSION_completion_fields CHECK ((actual_end_time IS NULL AND completed_by_user_account_id IS NULL AND final_condition_of_space IS NULL) OR (actual_end_time IS NOT NULL AND completed_by_user_account_id IS NOT NULL AND final_condition_of_space IS NOT NULL))
);
GO

-- Indexes on FK columns
CREATE NONCLUSTERED INDEX IX_USAGE_SESSION_booking_id ON dbo.USAGE_SESSION (booking_id);
CREATE NONCLUSTERED INDEX IX_USAGE_SESSION_checked_in_by_user_account_id ON dbo.USAGE_SESSION (checked_in_by_user_account_id);
CREATE NONCLUSTERED INDEX IX_USAGE_SESSION_completed_by_user_account_id ON dbo.USAGE_SESSION (completed_by_user_account_id);
GO

-- ------------------------------------------------------------
-- IMPLEMENTATION REQUIRED: Check-in user role restriction
-- BR: BR-14, BR-15
-- Tables: USAGE_SESSION, USER_ACCOUNT
-- Enforce: Check-in user must have role Facility Staff.
-- ------------------------------------------------------------
CREATE TRIGGER dbo.TR_USAGE_SESSION_CheckInRoleCheck ON dbo.USAGE_SESSION
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM inserted i
        JOIN dbo.USER_ACCOUNT u ON u.user_account_id = i.checked_in_by_user_account_id
        WHERE u.role <> N'Facility Staff'
    )
    BEGIN
        RAISERROR(N'Check-in user must be Facility Staff.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END;
END;
GO

-- ------------------------------------------------------------
-- IMPLEMENTATION REQUIRED: Completion user role restriction
-- BR: BR-16
-- Tables: USAGE_SESSION, USER_ACCOUNT
-- Enforce: Completion user, when present, must have role Facility Staff.
-- ------------------------------------------------------------
CREATE TRIGGER dbo.TR_USAGE_SESSION_CompletionRoleCheck ON dbo.USAGE_SESSION
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM inserted i
        JOIN dbo.USER_ACCOUNT u ON u.user_account_id = i.completed_by_user_account_id
        WHERE i.completed_by_user_account_id IS NOT NULL
          AND u.role <> N'Facility Staff'
    )
    BEGIN
        RAISERROR(N'Completion user must be Facility Staff.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END;
END;
GO

-- ------------------------------------------------------------
-- IMPLEMENTATION REQUIRED: Completion consistency
-- BR: BR-16
-- Tables: USAGE_SESSION
-- Enforce: Completion fields actual_end_time, completed_by_user_account_id, and
--          final_condition_of_space must be all null or all non-null.
-- Note: This rule is already enforced by CK_USAGE_SESSION_completion_fields.
--       Trigger shell retained to satisfy implementation-stub traceability.
-- ------------------------------------------------------------
CREATE TRIGGER dbo.TR_USAGE_SESSION_CompletionConsistency ON dbo.USAGE_SESSION
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM inserted i
        WHERE NOT (
            (i.actual_end_time IS NULL AND i.completed_by_user_account_id IS NULL AND i.final_condition_of_space IS NULL)
            OR
            (i.actual_end_time IS NOT NULL AND i.completed_by_user_account_id IS NOT NULL AND i.final_condition_of_space IS NOT NULL)
        )
    )
    BEGIN
        RAISERROR(N'Usage-session completion fields must be all null or all non-null.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END;
END;
GO

-- ============================================================
-- TABLE: MAINTENANCE_RECORD
-- Source: Logical Design §2.8
-- ============================================================
CREATE TABLE dbo.MAINTENANCE_RECORD (
    maintenance_record_id INT IDENTITY(1,1) NOT NULL,
    space_id INT NOT NULL,
    reporter_user_account_id INT NOT NULL,
    assigned_staff_user_account_id INT NULL,
    problem_description NVARCHAR(1000) NOT NULL,
    start_time DATETIME2(0) NOT NULL,
    completion_time DATETIME2(0) NULL,
    status NVARCHAR(40) NOT NULL,
    result_note NVARCHAR(1000) NULL,
    CONSTRAINT PK_MAINTENANCE_RECORD PRIMARY KEY (maintenance_record_id),
    CONSTRAINT FK_MAINTENANCE_RECORD_space_id FOREIGN KEY (space_id) REFERENCES dbo.SPACE(space_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_MAINTENANCE_RECORD_reporter_user_account_id FOREIGN KEY (reporter_user_account_id) REFERENCES dbo.USER_ACCOUNT(user_account_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_MAINTENANCE_RECORD_assigned_staff_user_account_id FOREIGN KEY (assigned_staff_user_account_id) REFERENCES dbo.USER_ACCOUNT(user_account_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT CK_MAINTENANCE_RECORD_time_order CHECK (completion_time IS NULL OR completion_time > start_time)
);
GO

-- Indexes on FK columns
CREATE NONCLUSTERED INDEX IX_MAINTENANCE_RECORD_space_id ON dbo.MAINTENANCE_RECORD (space_id);
CREATE NONCLUSTERED INDEX IX_MAINTENANCE_RECORD_reporter_user_account_id ON dbo.MAINTENANCE_RECORD (reporter_user_account_id);
CREATE NONCLUSTERED INDEX IX_MAINTENANCE_RECORD_assigned_staff_user_account_id ON dbo.MAINTENANCE_RECORD (assigned_staff_user_account_id);
GO

-- OPEN QUESTION Q7: Which roles may report maintenance issues?
-- Affected table/column: MAINTENANCE_RECORD.reporter_user_account_id
-- No role-restriction trigger has been added because permitted reporter roles are unresolved.

-- OPEN QUESTION Q8: Which roles may assign maintenance staff?
-- Affected table/column: MAINTENANCE_RECORD.assigned_staff_user_account_id
-- No assignment-authority trigger has been added because assigning authority is unresolved.

-- OPEN QUESTION Q9: What are the allowed values/transitions for MAINTENANCE_RECORD.status?
-- Affected table/column: MAINTENANCE_RECORD.status
-- No CHECK constraint has been added because the logical design says no upstream values are available.

-- OPEN QUESTION Q11: Does MAINTENANCE_RECORD.status automatically update SPACE.current_status?
-- Affected tables/columns: MAINTENANCE_RECORD.status, SPACE.current_status
-- No synchronization trigger has been added because the direction and status vocabulary are unresolved.

-- ============================================================
-- END OF DATABASE DEFINITION - G03
-- ============================================================
