/*
================================================================================
 Sample Data - Group 03
 Shared Campus Space Booking Database (Phase 1 schema)
================================================================================

 Input Analyzed:
   - outputs/05-db-definition-G03.sql (Phase 1 DDL: 14 tables, no triggers,
     no stored procedures, no manually created indexes).

 Execution Assumption:
   - This script must run on a clean database immediately after
     outputs/05-db-definition-G03.sql, with no other data present.
   - All surrogate `INT IDENTITY(1,1)` primary keys are left unassigned and
     are generated by SQL Server in strict insertion order. Lookup tables
     (ROLE, ACCOUNT_STATUS, DEPARTMENT, SPACE_STATUS, BOOKING_STATUS,
     FACILITY) and USER_ACCOUNT/SPACE are referenced downstream by natural
     unique columns (role_name, status_name, department_name, user_id,
     unique_space_code, facility_name) via scalar subqueries, so those
     references do not depend on identity numbering.
   - BOOKING_REQUEST has no natural unique column other than its surrogate
     PK, so APPROVAL_DECISION and USAGE_SESSION rows below reference it by
     the sequential identity values produced by the single BOOKING_REQUEST
     INSERT block in this script: booking_request_id 1-9, assigned in the
     literal row order written below (row 1 -> id 1, row 2 -> id 2, ...).
   - This script is not idempotent; it is designed for a single run against
     a freshly created schema. No IDENTITY_INSERT is used.

 Assumptions Carried Forward:
   - [upstream] DEPARTMENT and lookup entities (ROLE, ACCOUNT_STATUS,
     SPACE_STATUS, BOOKING_STATUS, MAINTENANCE_STATUS) are separate tables;
     sample rows are inserted for each.
   - [upstream] Only 'Approved' and 'Rejected' BOOKING_STATUS rows are used
     as APPROVAL_DECISION.decision_outcome_booking_status_id values; no
     other status is used as a decision outcome.
   - [upstream] "manager" in approval is the "facility manager" role; sample
     approval decisions are made by facility staff or facility manager
     accounts only, as a data-realism convention (not DDL-enforced in
     Phase 1).
   - [logical-stage] USER_ACCOUNT.email is treated as a candidate key,
     so every inserted email is distinct.
   - [ddl-stage] DEPARTMENT.head_user_account_id and
     USER_ACCOUNT.department_id form a circular FK. Resolved the same way
     as the DDL: DEPARTMENT rows are inserted first with
     head_user_account_id = NULL, USER_ACCOUNT rows are inserted next, then
     an UPDATE sets department heads for departments that have one.
   - [ddl-stage] No allowed-value CHECK exists for ACCOUNT_STATUS.status_name
     or MAINTENANCE_STATUS.status_name; the status values inserted below
     (Active/Inactive/Suspended and Reported/In progress/Completed,
     respectively) are sample-stage choices, not schema-enforced.

 Open Questions Carried Forward (from outputs/03-logical-design-G03.md
 Section 6 and outputs/05-db-definition-G03.sql OPEN QUESTION blocks; none
 are resolved by this data, only illustrated where relevant):
   - What is the account_status allowed-value set? Sample uses Active,
     Inactive, Suspended as representative values only.
   - What are the allowed maintenance status values and transitions?
     Sample uses Reported, In progress, Completed as representative values.
   - Which prior booking status/trigger/actor sets Cancelled or No-show?
     Sample includes one Cancelled booking (booking_request_id 6, previously
     Approved) and one No-show booking (booking_request_id 7, previously
     Approved) as plausible illustrations only; no transition rule is
     asserted or enforced.
   - What criteria determine whether a booking requires approval, and are
     any bookings exempt from the approval workflow? Sample always routes
     non-pending bookings through an APPROVAL_DECISION row; no exemption
     case is modeled because the criteria are unresolved.
   - Must every approved/rejected booking have exactly one APPROVAL_DECISION
     row? Sample gives each approved/rejected/cancelled/no-show booking
     exactly one decision row as a convention, not as an enforced rule.
   - Does opening a maintenance record automatically set SPACE.current_status
     to "Under maintenance"? Sample manually sets SPACE (space_id for
     CR-102) to "Under maintenance" and separately inserts a matching
     MAINTENANCE_RECORD row; no synchronization logic exists or is implied.
   - Should expected_number_of_participants be constrained to <=
     SPACE.capacity? Sample keeps all participant counts at or below the
     booked space's capacity as a realism convention, not an enforced rule.

 Trigger Compliance:
   - No triggers implemented in Phase 1; sample data only needs to satisfy
     PK/FK/UNIQUE/NOT NULL/CHECK.

 Sample Coverage / Traceability:
   - Roles covered (ROLE): student, lecturer, teaching assistant, facility
     staff, department administrator, facility manager - one or more
     USER_ACCOUNT row per role (user_id SV2021001, SV2021002, SV2022010,
     SV2021003, SV2022020 = student; GV001, GV002, GV003 = lecturer;
     TA001 = teaching assistant; STAFF001, STAFF002 = facility staff;
     ADMIN001, ADMIN002 = department administrator; MGR001 = facility
     manager).
   - Account statuses covered: Active (most users), Suspended (user_id
     SV2021003), Inactive (user_id GV003).
   - Departments covered: Computer Science and Business Administration
     (heads assigned to ADMIN001 and ADMIN002 respectively), Facilities
     Management (head assigned to MGR001), Electrical Engineering (no head
     assigned - exercises the optional 0..1 IS_MANAGED_BY relationship).
   - Space types covered (SPACE.space_type): classroom (CR-101, CR-102),
     computer laboratory (LAB-CS-201, LAB-CS-999), project laboratory
     (LAB-PJ-301), meeting room (MR-405, MR-201), auditorium (AUD-001),
     student workspace (SW-110).
   - Space statuses covered: Available/In use (most spaces), Under
     maintenance (unique_space_code CR-102), Temporarily closed
     (unique_space_code MR-201), Retired (unique_space_code LAB-CS-999).
   - Facilities covered: Projector, Whiteboard, Microphone, Computer,
     Livestreaming Equipment, Air Conditioner - all assigned to at least
     one SPACE via SPACE_FACILITY.
   - Booking statuses covered (BOOKING_REQUEST.booking_status_id), by
     booking_request_id: 1 = Completed, 2 = Checked in, 3 = Approved
     (upcoming, no session yet), 4 = Pending, 5 = Rejected, 6 = Cancelled,
     7 = No-show, 8 = Pending, 9 = Approved (upcoming, no session yet).
   - Booking purposes covered: lecture (1), workshop (2), meeting (3),
     examination (4), student activity (5, 8), administrative event (6, 9),
     seminar (7) - all 7 CK_BOOKING_REQUEST_purpose_of_use values used.
   - Exceptional cases and their IDs:
       * Rejected booking with rejection reason: booking_request_id 5,
         approval_decision tied to booking_request_id 5 (rejection_reason
         populated).
       * Cancelled booking: booking_request_id 6.
       * No-show booking: booking_request_id 7.
       * Completed booking with actual start/end time: booking_request_id 1,
         its USAGE_SESSION row (actual_start_time and actual_end_time both
         set, completed_by_user_account_id set).
       * Checked-in booking with in-progress usage session (no completion
         yet): booking_request_id 2, its USAGE_SESSION row (actual_end_time,
         final_condition_of_space, completed_by_user_account_id all NULL).
       * Space under maintenance: unique_space_code CR-102, with an
         in-progress MAINTENANCE_RECORD (problem_description about a
         projector/screen, completion_time NULL).
       * Temporarily closed space: unique_space_code MR-201 (no active
         maintenance record; closed independently, per open question above).
       * Retired space: unique_space_code LAB-CS-999, with a Reported
         (unresolved) MAINTENANCE_RECORD and an unassigned
         assigned_to_user_account_id (NULL), exercising the optional
         ASSIGNED_TO relationship.
       * Maintenance record fully completed: SPACE unique_space_code
         LAB-CS-201 (space remains Available/In use), with a Completed
         MAINTENANCE_RECORD (completion_time and result_note both set).
       * decision_note left NULL: approval decision tied to
         booking_request_id 3 (nullable column exercised).
================================================================================
*/

-- ============================================================================
-- 1. ROLE
-- ============================================================================
INSERT INTO dbo.ROLE (role_name) VALUES
    (N'student'),
    (N'lecturer'),
    (N'teaching assistant'),
    (N'facility staff'),
    (N'department administrator'),
    (N'facility manager');
GO

-- ============================================================================
-- 2. ACCOUNT_STATUS
-- ============================================================================
INSERT INTO dbo.ACCOUNT_STATUS (status_name) VALUES
    (N'Active'),
    (N'Inactive'),
    (N'Suspended');
GO

-- ============================================================================
-- 3. DEPARTMENT (head_user_account_id NULL for now; set after USER_ACCOUNT)
-- ============================================================================
INSERT INTO dbo.DEPARTMENT (department_name, head_user_account_id) VALUES
    (N'Computer Science', NULL),
    (N'Electrical Engineering', NULL),
    (N'Business Administration', NULL),
    (N'Facilities Management', NULL);
GO

-- ============================================================================
-- 4. USER_ACCOUNT
-- ============================================================================
INSERT INTO dbo.USER_ACCOUNT (user_id, full_name, email, phone_number, department_id, role_id, account_status_id)
VALUES
    (N'SV2021001', N'Nguyen Van An', N'an.nguyen@student.edu.vn', N'0901000001',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Computer Science'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'student'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active')),
    (N'SV2021002', N'Tran Thi Bich', N'bich.tran@student.edu.vn', N'0901000002',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Computer Science'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'student'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active')),
    (N'SV2022010', N'Le Hoang Nam', N'nam.le@student.edu.vn', N'0901000003',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Electrical Engineering'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'student'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active')),
    (N'GV001', N'Pham Thi Lan', N'lan.pham@university.edu.vn', N'0902000001',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Computer Science'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'lecturer'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active')),
    (N'GV002', N'Hoang Van Duc', N'duc.hoang@university.edu.vn', N'0902000002',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Electrical Engineering'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'lecturer'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active')),
    (N'GV003', N'Nguyen Thi Thanh', N'thanh.nguyen@university.edu.vn', N'0902000003',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Business Administration'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'lecturer'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Inactive')),
    (N'TA001', N'Vu Thi Mai', N'mai.vu@university.edu.vn', N'0903000001',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Computer Science'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'teaching assistant'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active')),
    (N'STAFF001', N'Do Van Hung', N'hung.do@facilities.edu.vn', N'0904000001',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Facilities Management'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'facility staff'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active')),
    (N'STAFF002', N'Ngo Thi Thu', N'thu.ngo@facilities.edu.vn', N'0904000002',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Facilities Management'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'facility staff'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active')),
    (N'ADMIN001', N'Bui Van Son', N'son.bui@university.edu.vn', N'0905000001',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Computer Science'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'department administrator'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active')),
    (N'ADMIN002', N'Dang Thi Hoa', N'hoa.dang@university.edu.vn', N'0905000002',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Business Administration'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'department administrator'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active')),
    (N'MGR001', N'Tran Van Phuc', N'phuc.tran@facilities.edu.vn', N'0906000001',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Facilities Management'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'facility manager'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active')),
    (N'SV2021003', N'Pham Thi Ngoc', N'ngoc.pham@student.edu.vn', N'0901000004',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Business Administration'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'student'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Suspended')),
    (N'SV2022020', N'Le Van Kiet', N'kiet.le@student.edu.vn', N'0901000005',
        (SELECT department_id FROM dbo.DEPARTMENT WHERE department_name = N'Electrical Engineering'),
        (SELECT role_id FROM dbo.ROLE WHERE role_name = N'student'),
        (SELECT account_status_id FROM dbo.ACCOUNT_STATUS WHERE status_name = N'Active'));
GO

-- ============================================================================
-- Deferred update: DEPARTMENT.head_user_account_id
-- (Electrical Engineering is left without a head to exercise the optional
-- 0..1 IS_MANAGED_BY relationship.)
-- ============================================================================
UPDATE dbo.DEPARTMENT
    SET head_user_account_id = (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'ADMIN001')
    WHERE department_name = N'Computer Science';

UPDATE dbo.DEPARTMENT
    SET head_user_account_id = (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'ADMIN002')
    WHERE department_name = N'Business Administration';

UPDATE dbo.DEPARTMENT
    SET head_user_account_id = (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'MGR001')
    WHERE department_name = N'Facilities Management';
GO

-- ============================================================================
-- 5. SPACE_STATUS
-- ============================================================================
INSERT INTO dbo.SPACE_STATUS (status_name) VALUES
    (N'Available'),
    (N'In use'),
    (N'Under maintenance'),
    (N'Temporarily closed'),
    (N'Retired');
GO

-- ============================================================================
-- 6. SPACE
-- ============================================================================
INSERT INTO dbo.SPACE (unique_space_code, space_name, space_type, building, floor, room_number, capacity, usage_policy, space_status_id)
VALUES
    (N'CR-101', N'Classroom 101', N'classroom', N'Building A', N'1', N'101', 40,
        N'General-purpose classroom; food and drink not permitted; must be vacated 15 minutes before the next booking.',
        (SELECT space_status_id FROM dbo.SPACE_STATUS WHERE status_name = N'Available')),
    (N'LAB-CS-201', N'Computer Lab 201', N'computer laboratory', N'Building B', N'2', N'201', 30,
        N'Software installation restricted to lab staff; all workstations must be logged off after use.',
        (SELECT space_status_id FROM dbo.SPACE_STATUS WHERE status_name = N'Available')),
    (N'LAB-PJ-301', N'Project Lab 301', N'project laboratory', N'Building B', N'3', N'301', 20,
        N'Reserved for project teams; equipment must be returned to storage racks after use.',
        (SELECT space_status_id FROM dbo.SPACE_STATUS WHERE status_name = N'In use')),
    (N'MR-405', N'Meeting Room 405', N'meeting room', N'Building C', N'4', N'405', 12,
        N'Whiteboard must be erased after use; catering allowed with prior approval.',
        (SELECT space_status_id FROM dbo.SPACE_STATUS WHERE status_name = N'Available')),
    (N'AUD-001', N'Main Auditorium', N'auditorium', N'Building D', N'Ground', N'001', 300,
        N'Requires facility manager sign-off for events exceeding 150 attendees.',
        (SELECT space_status_id FROM dbo.SPACE_STATUS WHERE status_name = N'Available')),
    (N'SW-110', N'Student Workspace 110', N'student workspace', N'Building A', N'1', N'110', 25,
        N'Open collaborative workspace; quiet hours enforced after 20:00.',
        (SELECT space_status_id FROM dbo.SPACE_STATUS WHERE status_name = N'Available')),
    (N'CR-102', N'Classroom 102', N'classroom', N'Building A', N'1', N'102', 35,
        N'General-purpose classroom; currently unavailable pending equipment repair.',
        (SELECT space_status_id FROM dbo.SPACE_STATUS WHERE status_name = N'Under maintenance')),
    (N'MR-201', N'Meeting Room 201', N'meeting room', N'Building C', N'2', N'201', 8,
        N'Small meeting room; temporarily closed for renovation.',
        (SELECT space_status_id FROM dbo.SPACE_STATUS WHERE status_name = N'Temporarily closed')),
    (N'LAB-CS-999', N'Old Computer Lab', N'computer laboratory', N'Building B', N'B1', N'999', 15,
        N'Decommissioned lab; retained for record-keeping only.',
        (SELECT space_status_id FROM dbo.SPACE_STATUS WHERE status_name = N'Retired'));
GO

-- ============================================================================
-- 7. FACILITY
-- ============================================================================
INSERT INTO dbo.FACILITY (facility_name) VALUES
    (N'Projector'),
    (N'Whiteboard'),
    (N'Microphone'),
    (N'Computer'),
    (N'Livestreaming Equipment'),
    (N'Air Conditioner');
GO

-- ============================================================================
-- 8. SPACE_FACILITY
-- ============================================================================
INSERT INTO dbo.SPACE_FACILITY (space_id, facility_id)
VALUES
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'CR-101'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Projector')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'CR-101'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Whiteboard')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'CR-101'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Air Conditioner')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'LAB-CS-201'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Computer')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'LAB-CS-201'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Projector')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'LAB-CS-201'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Air Conditioner')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'LAB-PJ-301'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Computer')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'LAB-PJ-301'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Whiteboard')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'MR-405'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Projector')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'MR-405'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Microphone')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'MR-405'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Air Conditioner')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'AUD-001'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Projector')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'AUD-001'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Microphone')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'AUD-001'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Livestreaming Equipment')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'AUD-001'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Air Conditioner')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'SW-110'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Computer')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'SW-110'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Whiteboard')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'CR-102'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Projector')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'CR-102'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Whiteboard')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'MR-201'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Projector')),
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'LAB-CS-999'), (SELECT facility_id FROM dbo.FACILITY WHERE facility_name = N'Computer'));
GO

-- ============================================================================
-- 9. BOOKING_STATUS
-- ============================================================================
INSERT INTO dbo.BOOKING_STATUS (status_name) VALUES
    (N'Pending'),
    (N'Approved'),
    (N'Rejected'),
    (N'Cancelled'),
    (N'Checked in'),
    (N'Completed'),
    (N'No-show');
GO

-- ============================================================================
-- 10. BOOKING_REQUEST
-- Row order below is significant: identity values 1-9 are assigned in this
-- exact order and referenced by number in APPROVAL_DECISION and
-- USAGE_SESSION further down (see Execution Assumption in the header).
-- ============================================================================
INSERT INTO dbo.BOOKING_REQUEST (requester_user_account_id, space_id, booking_status_id, requested_start_time, requested_end_time, purpose_of_use, expected_number_of_participants)
VALUES
    -- 1: Completed booking (lecture)
    ((SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'SV2021001'),
     (SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'CR-101'),
     (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Completed'),
     '2026-06-10T09:00:00', '2026-06-10T11:00:00', N'lecture', 35),
    -- 2: Checked in, in-progress session (workshop)
    ((SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'SV2021002'),
     (SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'LAB-CS-201'),
     (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Checked in'),
     '2026-07-05T14:00:00', '2026-07-05T16:00:00', N'workshop', 25),
    -- 3: Approved, upcoming (meeting) - decision_note left NULL
    ((SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'GV001'),
     (SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'MR-405'),
     (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Approved'),
     '2026-07-10T10:00:00', '2026-07-10T11:00:00', N'meeting', 8),
    -- 4: Pending (examination)
    ((SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'TA001'),
     (SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'CR-101'),
     (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Pending'),
     '2026-07-08T13:00:00', '2026-07-08T15:00:00', N'examination', 38),
    -- 5: Rejected (student activity) - rejection reason on its decision
    ((SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'SV2022010'),
     (SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'AUD-001'),
     (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Rejected'),
     '2026-07-03T08:00:00', '2026-07-03T10:00:00', N'student activity', 250),
    -- 6: Cancelled (administrative event) - was approved, then cancelled
    ((SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'ADMIN001'),
     (SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'MR-405'),
     (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Cancelled'),
     '2026-07-15T09:00:00', '2026-07-15T10:00:00', N'administrative event', 10),
    -- 7: No-show (seminar) - was approved, requester never checked in
    ((SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'GV002'),
     (SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'LAB-PJ-301'),
     (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'No-show'),
     '2026-06-20T08:00:00', '2026-06-20T10:00:00', N'seminar', 18),
    -- 8: Pending (student activity)
    ((SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'SV2022020'),
     (SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'SW-110'),
     (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Pending'),
     '2026-07-20T09:00:00', '2026-07-20T12:00:00', N'student activity', 20),
    -- 9: Approved, upcoming, extended duration (administrative event)
    ((SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'ADMIN002'),
     (SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'LAB-PJ-301'),
     (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Approved'),
     '2026-07-25T13:00:00', '2026-07-25T17:00:00', N'administrative event', 15);
GO

-- ============================================================================
-- 11. APPROVAL_DECISION
-- booking_request_id values below rely on the sequential order documented
-- in the BOOKING_REQUEST section above and in the header Execution
-- Assumption.
-- ============================================================================
INSERT INTO dbo.APPROVAL_DECISION (booking_request_id, decided_by_user_account_id, decision_outcome_booking_status_id, decision_time, decision_note, rejection_reason)
VALUES
    (1, (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'MGR001'),
        (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Approved'),
        '2026-06-08T10:00:00', N'Approved for scheduled lecture.', NULL),
    (2, (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'STAFF001'),
        (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Approved'),
        '2026-07-03T09:00:00', N'Approved, standard workshop booking.', NULL),
    (3, (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'MGR001'),
        (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Approved'),
        '2026-07-08T09:30:00', NULL, NULL),
    (5, (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'STAFF002'),
        (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Rejected'),
        '2026-07-01T15:00:00', N'Requested attendance is close to venue capacity.',
        N'Expected participant count (250) leaves no safety margin against the auditorium capacity and conflicts with a pre-scheduled maintenance inspection; please resubmit for a later date or a larger venue.'),
    (6, (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'MGR001'),
        (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Approved'),
        '2026-07-12T09:00:00', N'Approved administrative event.', NULL),
    (7, (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'STAFF001'),
        (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Approved'),
        '2026-06-18T09:00:00', N'Approved seminar booking.', NULL),
    (9, (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'MGR001'),
        (SELECT booking_status_id FROM dbo.BOOKING_STATUS WHERE status_name = N'Approved'),
        '2026-07-20T11:00:00', N'Approved extended project lab session.', NULL);
GO

-- ============================================================================
-- 12. USAGE_SESSION
-- booking_request_id values rely on the same sequential order as above.
-- ============================================================================
INSERT INTO dbo.USAGE_SESSION (booking_request_id, checked_in_by_user_account_id, completed_by_user_account_id, actual_start_time, initial_condition_of_space, actual_end_time, final_condition_of_space, usage_notes)
VALUES
    -- Booking 1: Completed, full lifecycle
    (1, (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'STAFF001'),
        (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'STAFF001'),
        '2026-06-10T09:05:00', N'Room clean, all equipment functional.',
        '2026-06-10T10:55:00', N'Room clean; projector bulb dim and flagged for maintenance.',
        N'Lecture ran smoothly with no incidents.'),
    -- Booking 2: Checked in, in-progress (no completion yet)
    (2, (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'STAFF002'),
        NULL,
        '2026-07-05T14:05:00', N'Workstations powered on and tested prior to session.',
        NULL, NULL, NULL);
GO

-- ============================================================================
-- 13. MAINTENANCE_STATUS
-- ============================================================================
INSERT INTO dbo.MAINTENANCE_STATUS (status_name) VALUES
    (N'Reported'),
    (N'In progress'),
    (N'Completed');
GO

-- ============================================================================
-- 14. MAINTENANCE_RECORD
-- ============================================================================
INSERT INTO dbo.MAINTENANCE_RECORD (space_id, reported_by_user_account_id, assigned_to_user_account_id, maintenance_status_id, problem_description, start_time, completion_time, result_note)
VALUES
    -- Active maintenance on the "Under maintenance" space (CR-102)
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'CR-102'),
     (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'GV001'),
     (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'STAFF001'),
     (SELECT maintenance_status_id FROM dbo.MAINTENANCE_STATUS WHERE status_name = N'In progress'),
     N'Projector does not power on; wall-mounted screen has a visible crack.',
     '2026-06-25T08:00:00', NULL, NULL),
    -- Unresolved, unassigned record on the retired space (LAB-CS-999)
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'LAB-CS-999'),
     (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'STAFF001'),
     NULL,
     (SELECT maintenance_status_id FROM dbo.MAINTENANCE_STATUS WHERE status_name = N'Reported'),
     N'Multiple workstations non-functional; lab flagged for decommissioning rather than repair.',
     '2026-05-01T09:00:00', NULL, NULL),
    -- Fully completed record on an available space (LAB-CS-201)
    ((SELECT space_id FROM dbo.SPACE WHERE unique_space_code = N'LAB-CS-201'),
     (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'STAFF002'),
     (SELECT user_account_id FROM dbo.USER_ACCOUNT WHERE user_id = N'STAFF001'),
     (SELECT maintenance_status_id FROM dbo.MAINTENANCE_STATUS WHERE status_name = N'Completed'),
     N'Air conditioner leaking water near workstation 5.',
     '2026-04-10T10:00:00', '2026-04-12T16:00:00', N'AC unit repaired; leak sealed and tested, no further issues observed.');
GO

-- ============================================================================
-- End of sample data script.
-- ============================================================================
